### ISSUE TITLE
Render PDF

### ISSUE THREAD

**Issue by oknoorap** [signintech/gopdf#10]
Can I render PDF on server (render output) not write to disk, 

In TCPDF (PHP) it has output method
```$pdf->Output('title.pdf', 'I');```

Can I do the same thing?

**Comment by oneplus1000** [comment]
You can do it like this. :smile:

```go
func ServeHTTP(w http.ResponseWriter, r *http.Request) {
	pdf := gopdf.GoPdf{}
	//--- do something ---
	w.Header().Set("Content-type", "application/pdf")
	w.Header().Set("content-disposition", "attachment;filename=\"abc.pdf\"")
	b := pdf.GetBytesPdf()
	w.Write(b)
}
```

**Comment by oknoorap** [comment]
okay,  :grinning: it will forced to download or it will show in browser?

**Comment by oneplus1000** [comment]
It forced to download. 
If you want to show in browser, use ...
```go
w.Header().Set("content-disposition", "filename=\"abc.pdf\"")
```

**Comment by oknoorap** [comment]
okay closed.
