### ISSUE TITLE
HTML and CSS

### ISSUE THREAD

**Issue by oknoorap** [signintech/gopdf#11]
is gopdf support HTML and CSS3?

**Comment by oneplus1000** [comment]
What do you mean by support HTML and CSS3?

**Comment by oknoorap** [comment]
Take a look tcpdf : http://www.tcpdf.org/examples.php
It supports html and css, not just plain text, so you can create PDF with html tag and css properties.
e.g:
```<p style="text-align: center"><span style="color: #cc0000">Text</span></p>```

That code, will displaying Text with red color, exactly looks like html, not just plain text.

**Comment by oneplus1000** [comment]
No, It does not supported.

**Comment by oknoorap** [comment]
okay thanks.
