### ISSUE TITLE
how to use ImportPageStream ?

### ISSUE THREAD

**Issue by madwolfcrazy** [signintech/gopdf#134]
`tempReader := bytes.NewReader(pdfTempFileBytes)
	pdf := gopdf.GoPdf{}
	pdf.Start(gopdf.Config{PageSize: SizeA4}) //595.28, 841.89 = A4

	pdf.AddPage()

	tpl1 := pdf.ImportPageStream(tempReader, 1, "/MediaBox")
	pdf.UseImportedTemplate(tpl1, 0, 0, SizeA4.W, SizeA4.H)`
error : cannot use tempReader (variable of type *bytes.Reader) as *io.ReadSeeker value in argument to pdf.ImportPageStreamcompiler
How should i convert the variable tempReader ?

**Comment by oneplus1000** [comment]
Could you try to open issue to [gofpdi](https://github.com/phpdave11/gofpdi) projecrt, I think this issue relate to [gofpdi](https://github.com/phpdave11/gofpdi) project.

**Comment by madwolfcrazy** [comment]
Solved! 
use this : 
`var tempReader io.ReadSeeker = bytes.NewReader(pdfTempFileBytes)`
