### ISSUE TITLE
How to improve quality when generating A4 PDF from single PNG image

### ISSUE THREAD

**Issue by rootVIII** [signintech/gopdf#152]
Thanks for the library. I'm having a slight issue where I am creating a PDF from single PNG images, and the resulting PDF is a bit blurry/off-color compared to the original. Is there any way to improve PDF quality/increase resolution?

The 2 relevant lines of code:
```
pdf.Start(gopdf.Config{PageSize: *gopdf.PageSizeA4})

pdf.Image(inputPath, 0, 0, &gopdf.Rect{W: 595, H: 842})

```

**section of the original PNG:**
https://drive.google.com/file/d/1do5INATEXby-UuVUYivhBVt0vg62JSQ-/view?usp=sharing

**section of the output PDF:**
https://drive.google.com/file/d/1DS0UddOU7OYndIRQeFs2-pig0zTRMLYw/view?usp=sharing

**Comment by ixuer** [comment]
Perhaps you need to prepare a bigger image.Like 1190*1684 or even bigger.

**Comment by vantaboard** [comment]
@oneplus1000 can you close this issue if it has been resolved? It seems like a user error and not related to the library.
