### ISSUE TITLE
Support for non-ASCII text

### ISSUE THREAD

**Issue by tajtiattila** [signintech/gopdf#16]
I tried putting non-ASCII text in a PDF by simply modifying the example, and use

    pdf.Cell(nil, "ÁÉÍÓÖŐÚÜŰ")

instead of

    pdf.Cell(nil, "Hello, world")

but nothing is visible. I used Roboto-Regular.ttf for my test from google fonts, which is known to have these characters.

Interestingly the text is not visible in the PDF (checked with Foxit Reader and Adobe Acrobat Reader DC), but the text is somehow there. It can be selected with the text tool and copied to the clipboard.

**Comment by signintech** [comment]
confirmed as bug, I'll looking into it this weekend.
