### ISSUE TITLE
Draw rectangle with round corner

### ISSUE THREAD

**Issue by fung-leung** [signintech/gopdf#193]
![image](https://user-images.githubusercontent.com/49734148/132934698-9f44d561-e033-48e7-89ef-596cc3a556a2.png)

I have create a function to draw rectangle with round corner by using the Polygon function. 

![image](https://user-images.githubusercontent.com/49734148/132934767-23ac325f-a0f7-4788-975b-f4ab43e9b0cd.png)

Can I contribute it to the code?

**Comment by oneplus1000** [comment]
Yes, of course, pull requests are welcome. :smile:
