### ISSUE TITLE
Not Rendering when Replacement Rune is not found

### ISSUE THREAD

**Issue by yoelsusanto** [signintech/gopdf#197]
In `v0.10.1`, when there is an undefined character, it will still be [registered](https://github.com/signintech/gopdf/blob/e4dc835a4fd377b7619dea0daa45beb13e1f3201/subset_font_obj.go#L132-L144) to `CharacterToGlyphIndex` with index 0. In the rendering, this will take effect as rendering .notdef character defined in the font.

When upgrading to `v.0.10.2`, `OnGlyphNotFoundSubstitute` is introduced so that we can specify what rune to be used for replacement. However, when the glyph for the replacement rune is also not found, it is not registered to `CharacterToGlyphIndex`. Thus, during rendering, instead of rendering `.notdef` glpyh, it will skip the undefined character resulting in blank.

I think the behavior when replacement glyph is also not found should be to render `.notdef` character.

`v.0.10.1`
![image](https://user-images.githubusercontent.com/32271826/136497196-5970d02b-0785-424a-8dab-7cbe2a88ea7c.png)
`v.0.10.2`
![image](https://user-images.githubusercontent.com/32271826/136497228-cfc6b238-dcf7-4e8f-bccc-810caaeccb57.png)

**Comment by oneplus1000** [comment]
Code has been merged into the master ( v0.10.3 ).
