### ISSUE TITLE
Generated PDFs won't print with cups-pdf

### ISSUE THREAD

**Issue by doncalamari** [signintech/gopdf#22]
Great package, but I'm having a small issue.
PDFs I create print fine when going through Adobe reader, but when trying to print them from the command line using the "lp" command the job immediately stops. The cups error log show that the PDF is missing the "startxref" section of the trailer. I checked it out in a hex editor and cups isn't lying. It's not there. I took a look at the code that is generating the trailer and it didn't look too hard to add it. Tested that fix and it works for me, so if you want to take a look I can open a PR or just send you a patch file. Whichever you prefer.

**Comment by oneplus1000** [comment]
Please send a pull request.

**Comment by doncalamari** [comment]
Done: https://github.com/signintech/gopdf/pull/23

It's pretty simple, but comments and/or criticism is welcome.

**Comment by oneplus1000** [comment]
Thank you.
