### ISSUE TITLE
MeasureTextWidth befor pdf.Cell caused char not found Error

### ISSUE THREAD

**Issue by mikeshimura** [signintech/gopdf#24]
w, err := pdf.MeasureTextWidth("志村正信")

caused char not found Error

but

pdf.Cell(nil, "志村正信")
w, err := pdf.MeasureTextWidth("志村正信")

passed without error

fyi

pdf.Curr.Font_ISubset.AddChars("志村正信")
w, err := pdf.MeasureTextWidth("志村正信")

also passed without error
I used this for workaround

**Comment by oneplus1000** [comment]
Issue fixed by commit c71cc8d895eac238390e38f48b087f7ba003febb
Thanks you.
