### ISSUE TITLE
Using mm instead of Points

### ISSUE THREAD

**Issue by rngallen** [signintech/gopdf#249]
Is it possible configure to use  "mm" as pdf dimensions instead of points? 
Like on gopdf 
`pdf := gofpdf.New("L", "mm", "A5", "")`

**Comment by lcscosta** [comment]
Yes, in pdf.start() we can configure some properties like page size and unit. 

As an example from README.md

```go
package main
import (
	"log"
	"github.com/signintech/gopdf"
)

func main() {

	pdf := gopdf.GoPdf{}
	pdf.Start(gopdf.Config{ PageSize: *gopdf.PageSizeA4 })  
	pdf.AddPage()
	err := pdf.AddTTFFont("wts11", "../ttf/wts11.ttf")
	if err != nil {
		log.Print(err.Error())
		return
	}

	err = pdf.SetFont("wts11", "", 14)
	if err != nil {
		log.Print(err.Error())
		return
	}
	pdf.Cell(nil, "您好")
	pdf.WritePdf("hello.pdf")

}
```

You can add the `Unit` in gopdf.Config

```go
...
	pdf := gopdf.GoPdf{}
	pdf.Start(gopdf.Config{ Unit: gopdf.UnitMM, PageSize: *gopdf.PageSizeA4 })  
	pdf.AddPage()
...
```

If you want to know more properties, in the documentation from Go pkgs we have:

https://pkg.go.dev/github.com/signintech/gopdf#Config
