### ISSUE TITLE
support negative x and y?

### ISSUE THREAD

**Issue by ShuaiGao** [signintech/gopdf#265]
When i draw a line(point A to point B) or set a pos(x,y), can i use negative x or y? 

Just like python list index, positive is from left to right, negative is right to left. Its easy to draw a right border just like left border.

**Comment by vantaboard** [comment]
Why not try it and see if it works?

**Comment by ShuaiGao** [comment]
I was tried, but it  doesn't seem to work. It's been too long, now i didn't need it.
