### ISSUE TITLE
Kerning support feature request

### ISSUE THREAD

**Issue by mikamiel** [signintech/gopdf#27]
Hi, gopdf developers, thanks for a nice native package. The only feature i miss is kerning support. Without kerning, generated pdf documents look non-professional. It's a weak point of almost all open source pdf libraries. Do you have plans to implement this at some point?
Especially it would be great if one could add/override internal font kerning values for arbitrary character pairs because many fonts lack thorough kerning spacings.

**Comment by oneplus1000** [comment]
I will look into it.

**Comment by oneplus1000** [comment]
I'm working on adding supports for font kerning at branch kerning (/signintech/gopdf/tree/kerning).

It's working now, please try it.

Use kerning from ttf:
```GO
    pdf := gopdf.GoPdf{}
	pdf.Start(gopdf.Config{Unit: "pt", PageSize: gopdf.Rect{W: 595.28, H: 841.89}}) //595.28, 841.89 = A4
	pdf.AddPage()
	pdf.AddTTFFontWithOption("Ubuntu", "../ttf/Ubuntu-L.ttf", gopdf.TtfOption{
		UseKerning: true,
	})
	pdf.SetFont("Ubuntu", "", 40)
	pdf.Cell(nil, "AVAWWA")
	pdf.WritePdf("kerning.pdf")
```

Override kerning:
```GO
    pdf := gopdf.GoPdf{}
	pdf.Start(gopdf.Config{Unit: "pt", PageSize: gopdf.Rect{W: 595.28, H: 841.89}}) //595.28, 841.89 = A4
	pdf.AddPage()
	pdf.AddTTFFontWithOption("Ubuntu", "../ttf/Ubuntu-L.ttf", gopdf.TtfOption{
		UseKerning: true,
	})
    pdf.KernOverride("Ubuntu", func(leftRune rune,
		rightRune rune,
		leftPair uint64,
		rightPair uint64,
		pairVal int64,
	) int64 {
         //return custom kerning value
		return pairVal * 2
	})
	pdf.SetFont("Ubuntu", "", 40)
	pdf.Cell(nil, "AVAWWA")
	pdf.WritePdf("kerning.pdf")
```

Note: Some functions, e.g. MeasureTextWidth, still doesn't use kerning to measure texts. I'm still working on it..

**Comment by mikamiel** [comment]
That's really amazing, thanks for your work!
I've tested it a bit, and have some questions:
1) Some programs output pdf documents with text having different kerning values (more balanced) than gppdf gives (at least visually). But that needs some investigation, i'm not sure yet.
2) I didn't get how to use KernOverride(). How can I feed it with an arbitrary pair of runes (sorry, i'm new with Go)? By default it takes first pair printed by Cell().
3) And the second problem with KernOverride() is that it returns int64, thus only integer coefficients are allowed which produces very big, unusable spacing steps. Maybe i miss the point?

**Comment by mikamiel** [comment]
I've made an image with the visual comparison (concerning the first question):
![kerning](https://cloud.githubusercontent.com/assets/18242513/14462057/bc63b202-00de-11e6-9012-2d911677a148.png)

**Comment by oneplus1000** [comment]
I've fixed the following problems in the latest commit:

- Convert kerning from font unit -> pdf unit. The space should display correctly now (I've only tested it with time new roman font, if you found something weird or incorrect please tell me.).

- Changed arguments to correct types, my bad.

- ```KernOverride()``` is for overriding the kerning value of each pair Here's the sample code..


```GO
pdf.KernOverride("HDZB_5", func(
		leftRune rune, /* character on left  */
		rightRune rune, /* character on right  */
		leftPair uint, /* index of character on left  */
		rightPair uint,  /* index of character on right  */
		pairVal int16, /* kerning value in font units */
	) int16 { /*return custom pair value*/
		
		if leftRune == 'A' && rightRune == 'V' {
			return 100
		} else if leftRune == 'A' && rightRune == 'W' {
			return 50
		} else if leftRune == 'A' && rightRune == 'k' {
			return 0
		}
		return pairVal 
})
```

```pairVal``` is the kerning value of the pair in font units (If this value is greater than zero, the characters will be moved apart. If this value is less than zero, the character will be moved closer together.

**Comment by mikamiel** [comment]
Now kerning works as it should, thanks.
One strange issue with `KernOverride()`. When I return absolute values (`return 100`) - all is ok, but trying something like `return pairVal*3` inverts spacings (moves characters closer instead of moving apart) and  opposite - negative values produce wider spacings.

**Comment by oneplus1000** [comment]
Hi mikamiel, I couldn't reproduce the problem. 
Returning negative value seems to work as intended (moves characters closer).

**Comment by mikamiel** [comment]
```go
	func main() {
		pdf := gopdf.GoPdf{}
		pdf.Start(gopdf.Config{Unit: "pt", PageSize: gopdf.Rect{W: 595.28, H: 841.89}}) //595.28, 841.89 = A4
		pdf.AddPage()
		pdf.AddTTFFontWithOption("times", "./ttf/times.ttf", gopdf.TtfOption{
			UseKerning: true,
		})
	
		pdf.SetFont("times", "", 40)
	
		pdf.KernOverride("times", func(
			leftRune rune, /* character on left  */
			rightRune rune, /* character on right  */
			leftPair uint, /* index of character on left  */
			rightPair uint, /* index of character on right  */
			pairVal int16, /* kerning value in font units */
		) int16 { /*return custom pair value*/
	
			return pairVal * (-3)
		})
	
		pdf.Cell(nil, "AVAW Wo")
		pdf.WritePdf("kern_override.pdf")
	}
```
![pairval-invrt](https://cloud.githubusercontent.com/assets/18242513/14703977/055ad8de-07cc-11e6-905f-3d8e1d9ca47e.png)

**Comment by mikamiel** [comment]
Doh! I understood now, using coefficient is a totally bad idea in that case. It's my mistake.

**Comment by oneplus1000** [comment]
Sorry that my first sample code is misleading :sob:

```MeasureTextWidth()```  still doesn't use kerning to measure texts. I'll work on it this weekend.
