### ISSUE TITLE
PNG image support

### ISSUE THREAD

**Issue by gambhiro** [signintech/gopdf#28]
Hello!

I followed the image embedding example and found that it only works with JPG images.

With PNG, the generated PDF doesn't show the image. The PDF is about the right size, so it must have read it in.

**Comment by oneplus1000** [comment]
I will look into it. after finish adding kerning support.

**Comment by ghiewa** [comment]
indeed, more, I ran into error

```
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/signintech/gopdf.paesePng(0x12652760, 0x1224f9a0, 0x734c40, 0x12256150, 0x1c5,
0x27d, 0x0, 0x0)
        E:/IDP/src/github.com/signintech/gopdf/image_obj_parse.go:270 +0x1ba2
```
