### ISSUE TITLE
An issue with precisely aligning characters over a baseline

### ISSUE THREAD

**Issue by mikamiel** [signintech/gopdf#29]
Hi, oneplus1000,
I've encountered a problem when aligning characters of different sizes/typefaces over a same baseline. Characters do not position *accurately*. 
Is there a way to precisely put arbitrary characters(of arbitrary sizes/typefaces) over a same baseline?
Maybe I'm doing something wrong? Is `TypoAscender()` the right metric in this case?
```go
import (
	"github.com/signintech/gopdf"
	"github.com/signintech/gopdf/fontmaker/core"
)

func getSpecTypoAsc(fontPath string, fontSize float64) float64 {
	var parser core.TTFParser
	parser.Parse(fontPath)
	typoAsc := float64(parser.TypoAscender()) * 1000.00 / float64(parser.UnitsPerEm())
	return typoAsc * fontSize / 1000.0
}

func main() {
	arialPath := "./ttf/arial.ttf"
	dejavuPath := "./ttf/DejaVuSerif.ttf"
	pdf := gopdf.GoPdf{}
	pdf.Start(gopdf.Config{Unit: "pt", PageSize: gopdf.Rect{W: 595.28, H: 841.89}})
	pdf.AddPage()
	pdf.AddTTFFont("arial", arialPath)
	pdf.AddTTFFont("deja", dejavuPath)
	pdf.SetX(0) 
	pdf.SetY(0)
	pdf.SetFont("arial", "", 60)
	pdf.Cell(nil, "h")
	pdf.SetFont("arial", "", 30)
	pdf.SetY(getSpecTypoAsc(arialPath, 60) - getSpecTypoAsc(arialPath, 30))
	pdf.Cell(nil, "h")
	pdf.SetFont("deja", "", 20)
	pdf.SetY(getSpecTypoAsc(arialPath, 60) - getSpecTypoAsc(dejavuPath, 20))
	pdf.Cell(nil, "h")		
	pdf.WritePdf("baseline.pdf")
}
```
![baseline-dif](https://cloud.githubusercontent.com/assets/18242513/14814470/db293ebe-0bbf-11e6-91d4-bde80e487324.png)

**Comment by oneplus1000** [comment]
Hi mikamiel, Thanks for your issue report. I will check it out. 

Anyway please replace ```pdf.Curr.X``` and ```pdf.Curr.Y``` with ```pdf.SetX()``` and ```pdf.SetY()``` accordingly because the pdf.Curr should be the private variable but I was new with golang at the time that gopdf was launched so that I forgot to correct (I have plan to clean some legacy code soon) 
however this is not related to this issue.

**Comment by mikamiel** [comment]
Ok, I've replaced it in example to not confuse someone else.

**Comment by mikamiel** [comment]
I found a detailed article about vertical font metrics maybe it can help:
https://www.glyphsapp.com/tutorials/vertical-metrics

**Comment by oneplus1000** [comment]
Hi mikamiel, I've fixed the character height problems. It should correct now.
Also, I've add ```pdf.Text(txt string)``` function that renders text using Y as baseline.

```go
pdf.SetX(10)
pdf.SetY(50)
pdf.SetFont("arial", "", 60)
pdf.Text("h")
pdf.SetFont("arial", "", 30)
pdf.Text("h")
pdf.SetFont("deja", "", 20)
```

**Comment by mikamiel** [comment]
Thanks, it would significantly simplify working with text. I'll test it more closely this week. Does master includes now `pdf.Text()`, kerning support and `MeasureTextWidth() with kerning taken into account`?

**Comment by oneplus1000** [comment]
Yes, it all fixed ( and merged into master ).
