### ISSUE TITLE
How can I make the text automatically wrap to the next line when the characters exceed the line limit

### ISSUE THREAD

**Issue by Guo-Chenxu** [signintech/gopdf#307]
i want to make the text automatically wrap to the next line when it exceed the limit

go version: 1.20.14
gopdf version: 0.27.1

my code is here
```go
func TestPdf(t *testing.T) {
	pdf := gopdf.GoPdf{}
	pdf.Start(gopdf.Config{PageSize: *gopdf.PageSizeA4})
	pdf.AddPage()

	err := pdf.AddTTFFont("SimHei", "SimHei.ttf")
	if err != nil {
		t.Errorf("add font err, %+v", err)
	}
	pdf.SetFont("SimHei", "", 14)

	pdf.Cell(nil, "字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符字符")

	err = pdf.WritePdf("./test.pdf")
	if err != nil {
		t.Error(err)
	}
}
```

i got a pdf like this
<img width="696" alt="image" src="https://github.com/user-attachments/assets/a8af8885-f36b-47f5-b582-0bc03a1bf546">

i want to make it automatically make a new line when it need

thank you for your help

**Comment by vitorf7** [comment]
@Guo-Chenxu I was just facing the same problem. Did you manage to find a solution?

**Comment by Guo-Chenxu** [comment]
> @Guo-Chenxu I was just facing the same problem. Did you manage to find a solution?

I handle line breaks manually😂. (By default, one line is approximately 82 English characters.)
