### ISSUE TITLE
can not print chinese character "张"

### ISSUE THREAD

**Issue by puma007** [signintech/gopdf#34]
I use your library for generating PDF，but it can not print chinese character "张"，other chinese characters can print,why? 
I refer to your sample code,and add the chinese font wts11.ttf.
`pdf.AddTTFFont("HDZB_5", "../ttf/wts11.ttf")
pdf.SetFont("HDZB_5", "", 14)`

**Comment by oneplus1000** [comment]
I think file 'wts11.ttf' not contain character '张' (code=24352). 
![24352](https://cloud.githubusercontent.com/assets/1155104/18616743/20b7f6da-7deb-11e6-8275-4f2aa4af0167.png)

**Comment by puma007** [comment]
@oneplus1000 Thanks,I have changed the file 'wts11.ttf' to 'CloudKaiTiGBK.ttf'  , and then solved the problem!
