### ISSUE TITLE
A4

### ISSUE THREAD

**Issue by hsulei** [signintech/gopdf#40]
if i set pdf.Start(gopdf.Config{PageSize: gopdf.Rect{W: 2480, H: 3508}})  , 
is this setting for A4 page?

**Comment by oneplus1000** [comment]
```go
pdf.Start(gopdf.Config{ PageSize: gopdf.Rect{W: 595.28, H: 841.89}}) //595.28, 841.89 = A4
```

**Comment by hsulei** [comment]
Thanks。
i make a mistake，`func (gp *GoPdf) Image(picPath string, x float64, y float64, rect *Rect)  error`  。 in this function，i forget the parameter ` rect` ，when i draw a image (size :1880x60)
