### ISSUE TITLE
有表格例子吗？

### ISSUE THREAD

**Issue by piaohailin** [signintech/gopdf#43]
项目中有大量的不规则表格需求，有这方面的API吗？

**Comment by Tom-Kail** [comment]
目前没有发现直接用于表格的API，但是可以用线画出表格的轮廓，然后自己填充数据，就是麻烦了一些

**Comment by khlipeng** [comment]
我就是自己画线，在定位填充数据

**Comment by tiechui1994** [comment]
可以参考 https://github.com/tiechui1994/gopdf 这个项目, 目前可以进行表格自动化处理
