### ISSUE TITLE
Alternative ways to add a font

### ISSUE THREAD

**Issue by dvorakluk** [signintech/gopdf#44]
Hi, it would be really nice if we can add a font from []byte (or io.Reader), so fonts can be embeded directly into the binary (via go-bindata etc..)

**Comment by oneplus1000** [comment]
Hi dvorakluk, I created 2 new function.
```go
 func (gp *GoPdf) AddTTFFontByReader(family string, rd io.Reader)  { ... }
```
and 
```go
 func (gp *GoPdf) AddTTFFontByReaderWithOption(family string, rd io.Reader, option TtfOption) { ... }
```
I need a few days for testing before merging this code into master so now I push this new code on branch [font_with_reader](https://github.com/signintech/gopdf/tree/font_with_reader)

**Comment by dvorakluk** [comment]
Thank you, I have tested it and everything looks allright

**Comment by oneplus1000** [comment]
merged into master.:smile:
