### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by amlwwalker** [signintech/gopdf#45]
PDF documents are able to contain and run javascript. Is there any way to do this in this library?

**Comment by oneplus1000** [comment]
Hi amlwwalker, I create function SetJs(...) for embed js in PDF. I push this code to branch ["javascript"](https://github.com/signintech/gopdf/tree/javascript). 
```go
 pdf := gopdf.GoPdf{}
 pdf.Start(gopdf.Config{PageSize: gopdf.Rect{W: 595.28, H: 841.89}}) 
 pdf.AddPage()
 ...
 pdf.SetJs("app.alert('Hi');")
 pdf.WritePdf("js.pdf")
```
and this is result.

![screenshot at 2016-12-23 23-43-06](https://cloud.githubusercontent.com/assets/1155104/21458547/073c8c0a-c96a-11e6-8f21-6365145c346d.png)
