### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by whyrusleeping** [signintech/gopdf#51]
Thanks for this lib, it works quite well :)

Could you add a license to the code? Preferrably MIT or some BSD one. I'd like to use this in a project but cant if theres no license file in the repo.

Thanks in advance!

**Comment by MatthewSH** [comment]
https://github.com/signintech/gopdf/blob/master/LICENSE

**Comment by whyrusleeping** [comment]
I'm obviously great at reading. Thanks (in my defense i was looking after lowercase L)
