### ISSUE TITLE
How does the text wrap in the specified range?

### ISSUE THREAD

**Issue by khlipeng** [signintech/gopdf#52]
How does the text wrap in the specified range?

**Comment by khlipeng** [comment]
I use lines to draw the table, in the cell within the text automatically wrap

**Comment by oneplus1000** [comment]
gopdf  doesn't have textwrap, but you can use function **MeasureTextWidth("test test test")** to implement your own textwarp.
```go
err := pdf.AddTTFFont("loma", "../loma.ttf")
//handle error
err = pdf.SetFont("loma", "", 14)
//handle error
text01 := "test test test"
textwidth, _ := pdf.MeasureTextWidth(text01)
```
