### ISSUE TITLE
Question: Cell fill color

### ISSUE THREAD

**Issue by Roosh513** [signintech/gopdf#53]
I am trying to figure out a way to set the fill color of a cell, much like the way you would draw a filled rectangle.

`pdf.RectFromUpperLeftWithStyle(x, y, 200.28, 150.89, "FD")`

Thus far, I have not seen a way to do this. I want to build a PDF with tabular data, and need to be able to fill the cell background with a certain color. As far as I can tell, I'm stuck with a white background for cells.

**Comment by oneplus1000** [comment]
please try this
```go
pdf.SetFillColor(0, 255, 0) //setup fill color
pdf.RectFromUpperLeftWithStyle(x, y, 200.28, 150.89, "FD")
```

**Comment by Roosh513** [comment]
That works as far as a fill color. However, if I want text in the cell, I can't find a way to get the text to render inside.

**Comment by oneplus1000** [comment]
I just push sample code to https://github.com/oneplus1000/gopdfsample/tree/master/rect
![screenshot at 2017-06-06 23 20 33](https://user-images.githubusercontent.com/1155104/26840197-7ea77224-4b0f-11e7-8144-9e53c2294438.png)

**Comment by Roosh513** [comment]
This is helpful, thank you for taking the time to put the example together! I'll go ahead and close this out.
