### ISSUE TITLE
Create page how to implement 90 ° flip

### ISSUE THREAD

**Issue by khlipeng** [signintech/gopdf#55]
Create page how to implement 90 ° flip？

**Comment by khlipeng** [comment]
In one document, take a few pages out horizontally

**Comment by oneplus1000** [comment]
do you mean?
![img_20170617_134519019_hdr](https://user-images.githubusercontent.com/1155104/27252282-86aa4532-5384-11e7-847e-c8f893586c05.jpg)

**Comment by khlipeng** [comment]
page 2

**Comment by oneplus1000** [comment]
I have just added a new function.
```go
pdf.AddPageWithOption(gopdf.PageOption{PageSize: gopdf.Rect{W: 841.89, H: 595.28}})
```
here is the sample code -> https://github.com/oneplus1000/gopdfsample/tree/master/pageopt

**Comment by khlipeng** [comment]
@oneplus1000 Thank you
