### ISSUE TITLE
When imported pictures, how to use [] byte

### ISSUE THREAD

**Issue by khlipeng** [signintech/gopdf#56]
When imported pictures, how to use [] byte

**Comment by khlipeng** [comment]
How do I import a binary image directly?

**Comment by oneplus1000** [comment]
i just push new code for draw image by []byte to branch **[img_by_byte](https://github.com/signintech/gopdf/tree/img_by_byte)** 

## Sample
```go
pdf := gopdf.GoPdf{}
//...
imgH, err := gopdf.ImageHolderByBytes(bytesOfImg)
if err != nil {
	return err
}
pdf.ImageByHolder(imgH, 200, 50, nil)
//...
pdf.WritePdf("image.pdf")
```

**Comment by oneplus1000** [comment]
Code is merged into master
see sample here: https://github.com/oneplus1000/gopdfsample/blob/master/image/image.go

**Comment by khlipeng** [comment]
@oneplus1000 Thanks

**Comment by khlipeng** [comment]
@oneplus1000 go get -u github.com/signintech/gopdf
../github.com/signintech/gopdf/gopdf.go:75: undefined: zlib.HuffmanOnly
