### ISSUE TITLE
invalid xref created

### ISSUE THREAD

**Issue by mtcxgarble** [signintech/gopdf#58]
mupdf, xpdf (open source pdf viewers) complain about an invalid xref table, but they can fix the problem.  
PDF-specification states that the "end of line" marker must be two characters wide. 

That I can fix myself :) 
Pull request: https://github.com/signintech/gopdf/pull/57

**Comment by oneplus1000** [comment]
Thank you :smile:

**Comment by mtcxgarble** [comment]
You are very welcome :) 
Thank you for accepting the pull request.  
Will close this issue now.
