### ISSUE TITLE
Failed to go get

### ISSUE THREAD

**Issue by darkengine** [signintech/gopdf#62]
Error happened when running go get under window 10 64bit

$ go get -u github.com/signintech/gopdf
# github.com/signintech/gopdf
github.com\signintech\gopdf\gopdf.go:75: undefined: zlib.HuffmanOnly

need to get zlib library before gopdf?

**Comment by darkengine** [comment]
For more infomation, all codes are downloaded already.

Modify the following code:

gopdf.go, line 75:
if level < zlib.HuffmanOnly 

form HuffmanOnly  to DefaultCompression solve the problem.

**Comment by oneplus1000** [comment]
fixed 436554a518404c5242c1eca92b3aac2e30515513
