### ISSUE TITLE
Different file hashes with same content

### ISSUE THREAD

**Issue by everimbaq** [signintech/gopdf#65]
I generate files twice with same content, but the file md5 hashes are different
I want to use md5 to verify the content has not been modified, Is there any way to acheive this?

**Comment by oneplus1000** [comment]
Because maps in the Golang have no order.
Now I push a new code that changes from map to slice in branch "[issue_65](https://github.com/signintech/gopdf/tree/issue_65)".
(I will merge to master after I'm sure it does not affect the old code)

**Comment by oneplus1000** [comment]
fixed  dab786e77295df4c8a38d91c368eb99fb1d7cabd
