### ISSUE TITLE
large PDF causes out of memory

### ISSUE THREAD

**Issue by missdeer** [signintech/gopdf#74]
Hi,

I'm using gopdf package to generate PDF documents, but if the PDF document is very large, such as more than 10000 A4 pages, the program eats many memory then crashes due to out of memory. Any suggestions? Thanks!

Regards,
Fan

**Comment by oneplus1000** [comment]
Hi,
Can you try to switch branch to  ["CaptainCodeman-writer"](https://github.com/signintech/gopdf/tree/CaptainCodeman-writer), this branch I merged from  ["PR #71 Reduce Memory Use"](https://github.com/signintech/gopdf/pull/71)

**Comment by missdeer** [comment]
@oneplus1000 i have tried  "CaptainCodeman-writer" branch, it seems that memory usage is reduced, but when I try to merge those new generated PDF files by [unidoc](https://github.com/unidoc/unidoc), error message 'Missing catalog' is printed. Is there something that not compatible?

**Comment by oneplus1000** [comment]
please pull (branch "CaptainCodeman-writer") and try again, I just fixed gopdf that created wrong xref table.

**Comment by missdeer** [comment]
@oneplus1000 it works fine now, thanks.
