### ISSUE TITLE
Printing png files

### ISSUE THREAD

**Issue by krdkv** [signintech/gopdf#80]
Good day!

Having problems printing out png images:

```
pdf := gopdf.GoPdf{}
pdf.Start(gopdf.Config{ PageSize: gopdf.Rect{W: 505, H: 840}})
pdf.AddPage()
pdf.Image("img/logo.png", 0, 0, &gopdf.Rect{W: 500, H: 500});
```

– doesn't print anything.

```
bytesOfImg, err := ioutil.ReadFile("img/logo.png")
if err != nil {
    log.Print("Can't read file")
    log.Print(err)
    return
}

imgH, err := gopdf.ImageHolderByBytes(bytesOfImg)
if err != nil {
    log.Print("Couldn't create holder")
    log.Print(err)
    return
}

err = pdf.ImageByHolder(imgH, 0, 0, nil)
if err != nil {
    log.Print("Couldn't print out image")
    log.Print(err)
    return
}
```

– and this code prints "Couldn't print out image", "EOF"

Thank you!

**Comment by krdkv** [comment]
My guess is that the problem is with the image.
I'm able to print gopher02.png (from your test folder) but I get the same result as above for this image:
https://raw.githubusercontent.com/signintech/gopdf/master/test/res/PNG_transparency_demonstration_1.png

**Comment by krdkv** [comment]
Figured it out. When exporting png file must have colour profile embedded.
Thanks a lot!

**Comment by oneplus1000** [comment]
Thank you for bug reported. Now I've fixed errors to get gopdf support png that doesn't has color profile.

**Comment by krdkv** [comment]
Thank you so much!
