### ISSUE TITLE
Fill in form fields

### ISSUE THREAD

**Issue by apremalal** [signintech/gopdf#83]
Hello Devs,

Is there any plan to ad form filling capabilities to the library?

**Comment by oneplus1000** [comment]
if you mean inject some text in to pdf file, i have other project [signintech/pdft ](https://github.com/signintech/pdft)
*It is a project I use in personal so i tested only with pdf that i use.

**Comment by apremalal** [comment]
@oneplus1000 thanks. yeah found it. Thanks for the awesome work!.
