### ISSUE TITLE
Strange SetTextColor

### ISSUE THREAD

**Issue by alexesDev** [signintech/gopdf#93]
pdf.SetTextColor(124, 85, 47) set text color to black
pdf.SetTextColor(**125**, 85, 47) as expected
pdf.SetTextColor(124, 85, **48**) as expected
why?

```
package main

import "github.com/signintech/gopdf"

func main() {
	pdf := gopdf.GoPdf{}
	pdf.Start(gopdf.Config{PageSize: gopdf.Rect{W: 595.28, H: 841.89}}) //595.28, 841.89 = A4
	pdf.AddPage()
	pdf.SetTextColor(124, 85, 47)
	pdf.AddTTFFont("circe", "./Circe-Bold.ttf")
	pdf.SetFont("circe", "", 14)
	pdf.Cell(nil, "Hello")
	pdf.WritePdf("hello.pdf")
}
```

**Comment by oneplus1000** [comment]
thank you for reporting this issue :smiley:, now it fixed. :relaxed:  
(commit 4d0bf4301b565a242a52b1db53306d34d42098f9)

**Comment by alexesDev** [comment]
Wow :smile: I'll go buy a lottery ticket :smile:
